services:

  garnet:
    image: ghcr.io/microsoft/garnet
    volumes:
      - garnet_data:/data

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper

  api:
    build:
      context: ../../
      dockerfile: ./src/api/Synapse.Api.Server/Dockerfile
    environment:
      CONNECTIONSTRINGS__REDIS: ${GARNET_URI}
      SYNAPSE_DASHBOARD_SERVE: 'true'
      SYNAPSE_API_AUTH_TOKEN_FILE: /app/tokens.yaml
      SYNAPSE_API_JWT_AUTHORITY: http://api:8080
      SYNAPSE_API_CLOUD_EVENTS_ENDPOINT: https://webhook.site/a4aff725-0711-48b2-a9d2-5d1b806d04d0
      SYNAPSE_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./config/tokens.yaml:/app/tokens.yaml
    ports:
      - 8080:8080
    depends_on:
      - garnet

  operator:
    build:
      context: ../../
      dockerfile: ./src/operator/Synapse.Operator/Dockerfile
    environment:
      CONNECTIONSTRINGS__REDIS: ${GARNET_URI}
      SYNAPSE_OPERATOR_NAMESPACE: default
      SYNAPSE_OPERATOR_NAME: operator-1
      SYNAPSE_RUNNER_API: http://api:8080
      SYNAPSE_RUNNER_LIFECYCLE_EVENTS: 'true'
      SYNAPSE_RUNNER_CONTAINER_PLATFORM: docker
      DOCKER_HOST: unix:///var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    depends_on:
      - garnet

  correlator:
    build:
      context: ../../
      dockerfile: ./src/correlator/Synapse.Correlator/Dockerfile
    environment:
      CONNECTIONSTRINGS__REDIS: ${GARNET_URI}
      SYNAPSE_CORRELATOR_NAMESPACE: default
      SYNAPSE_CORRELATOR_NAME: correlator-1
    ports:
      - 8081:8080
    depends_on:
      - garnet

volumes:

  garnet_data:
    driver: local

networks:

  default:
    name: synapse